<a href="https://colab.research.google.com/github/adityajain2407/DAV-1-apr23/blob/main/apr23_pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# !wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

In [16]:
df = pd.read_csv("mckinsey.csv")

In [3]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [4]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head(10)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [7]:
df.tail()

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [8]:
df.tail(10)

       country  year  population continent  life_exp     gdp_cap
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [9]:
df.shape

(1704, 6)

In [10]:
rows = df.shape[0]
cols = df.shape[1]

In [11]:
print(rows)

1704

In [12]:
print(cols)

6

In [13]:
df["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [14]:
type(df["country"])

pandas.core.series.Series

In [15]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [ ]:
#     country	  year	population	continent	life_exp	gdp_cap
# 0	Afghanistan	1952	8425333	    Asia	    28.801	  779.445314
# 1	Afghanistan	1957	9240934	    Asia	    30.332	  820.853030
# 2	Afghanistan	1962	102267083	  Asia	    31.997	  853.100710

In [20]:
#row-oriented approach
sample_df = pd.DataFrame(
              [['Afghanistan',1952, 8425333, 'Asia', 28.801, 779.445314 ],
              ['Afghanistan',1957, 9240934, 'Asia', 30.332, 820.853030 ],
              ['Afghanistan',1962, 102267083, 'Asia', 31.997, 853.100710 ],
               ['Afghanistan',1962, 102267083, 'Asia', 31.997, 853.100710 ]],

             columns=['country','year','population','continent','life_exp','gdp_cap']
    )

In [21]:
sample_df

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962   102267083      Asia    31.997  853.100710
3  Afghanistan  1962   102267083      Asia    31.997  853.100710

In [22]:
#row-oriented approach
sample_df = pd.DataFrame(
              [['Afghanistan',1952, 8425333, 'Asia', 28.801, 779.445314 ]],

             columns=['country','year','population','continent','life_exp','gdp_cap']
    )

In [23]:
sample_df

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314

In [24]:
#row-oriented approach
sample_df = pd.DataFrame(
              ['Afghanistan',1952, 8425333, 'Asia', 28.801, 779.445314 ],

             columns=['country','year','population','continent','life_exp','gdp_cap']
    )

ValueError: ignored

In [25]:
#column-oriented appraoch

df2 = pd.DataFrame(
              {'country':['Afghanistan', 'Afghanistan'],
               'year':[1952,1957],
              'population':[842533, 9240934],
               'continent':['Asia', 'Asia'],
              'life_exp':[28.801, 30.332],
               'gdp_cap':[779.445314, 820.853030]
               }
    )

df2

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952      842533      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [26]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [27]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [28]:
df.columns[0]

'country'

In [29]:
df.columns[2]

'population'

In [30]:
df["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [31]:
#not used - but works
df.country

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [32]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [34]:
df2 = df[ ["year" , "continent"] ].head()

In [35]:
df2

   year continent
0  1952      Asia
1  1957      Asia
2  1962      Asia
3  1967      Asia
4  1972      Asia

In [36]:
#basic operations on column

In [39]:
unique_country = df["country"].unique() #all the unique values in a col

In [40]:
unique_country

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [41]:
df["country"].nunique()

142

In [42]:
df["country"].value_counts()

Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: country, Length: 142, dtype: int64

In [43]:
#renaming a column

In [44]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [45]:
df.rename(
    {"population" : "Population",
     "country" : "Country"}
    )

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [46]:
df.rename(
    {"population" : "Population",
     "country" : "Country"},

    axis = 1
    )

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
# df.rename({"population" : "Population", "country" : "Country"}, axis = 1)

In [47]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [48]:
df_renamed = df.rename({"population" : "Population", "country" : "Country"}, axis = 1)

In [49]:
df_renamed.head()

       Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [50]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [51]:
df.rename({"population" : "Population", "country" : "Country"}, axis = 1, inplace = True)

In [52]:
df.head()

       Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [53]:
#deleting the columns

In [54]:
df.drop("continent", axis = 1)

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [55]:
df.head()

       Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [56]:
df.drop("continent", axis = 1, inplace = True)

In [57]:
df.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [58]:
#way2 to drop a column

df_renamed.head()

       Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [60]:
df_renamed.drop(columns = ["continent"])

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [61]:
df_renamed.head()

       Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [62]:
df_renamed.drop(columns = ["continent"], inplace = True)

In [63]:
df_renamed.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [64]:
df_renamed.drop(columns = ["Country", "Population"], inplace = True)

In [65]:
df_renamed.head()

   year  life_exp     gdp_cap
0  1952    28.801  779.445314
1  1957    30.332  820.853030
2  1962    31.997  853.100710
3  1967    34.020  836.197138
4  1972    36.088  739.981106

In [66]:
#creating a new column

In [67]:
df.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [68]:
df["year+7"] = df["year"] + 7

In [69]:
df.head()

       Country  year  Population  life_exp     gdp_cap  year+7
0  Afghanistan  1952     8425333    28.801  779.445314    1959
1  Afghanistan  1957     9240934    30.332  820.853030    1964
2  Afghanistan  1962    10267083    31.997  853.100710    1969
3  Afghanistan  1967    11537966    34.020  836.197138    1974
4  Afghanistan  1972    13079460    36.088  739.981106    1979

In [70]:
df["gdp"] = df["gdp_cap"]*df["Population"]
df.head()

       Country  year  Population  life_exp     gdp_cap  year+7           gdp
0  Afghanistan  1952     8425333    28.801  779.445314    1959  6.567086e+09
1  Afghanistan  1957     9240934    30.332  820.853030    1964  7.585449e+09
2  Afghanistan  1962    10267083    31.997  853.100710    1969  8.758856e+09
3  Afghanistan  1967    11537966    34.020  836.197138    1974  9.648014e+09
4  Afghanistan  1972    13079460    36.088  739.981106    1979  9.678553e+09

In [72]:
df["new"] = [ i for i in range(1704)]
df

,Country,year,Population,life_exp,gdp_cap,year+7,gdp,new
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09,0
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09,1
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09,2
3,Afghanistan,1967,11537966,34.020,836.197138,1974,9.648014e+09,3
4,Afghanistan,1972,13079460,36.088,739.981106,1979,9.678553e+09,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1994,6.508241e+09,1699
1700,Zimbabwe,1992,10704340,60.377,693.420786,1999,7.422612e+09,1700
1701,Zimbabwe,1997,11404948,46.809,792.449960,2004,9.037851e+09,1701
1702,Zimbabwe,2002,11926563,39.989,672.038623,2009,8.015111e+09,1702
1703,Zimbabwe,2007,12311143,43.487,469.709298,2014,5.782658e+09,1703

In [73]:
df.drop(columns = ["year+7" , "gdp", "new"], inplace= True)
df.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [74]:
#dataframe indexing

In [75]:
df.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [77]:
df.columns

Index(['Country', 'year', 'Population', 'life_exp', 'gdp_cap'], dtype='object')

In [78]:
df.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703])

In [79]:
n= df.shape[0]

df.index = [i for i in range(1, n+1)]

In [80]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [81]:
sample = df.head()

In [82]:
sample

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [83]:
sample.index = ["a", "b", "c", "d", "e"]
sample

       Country  year  Population  life_exp     gdp_cap
a  Afghanistan  1952     8425333    28.801  779.445314
b  Afghanistan  1957     9240934    30.332  820.853030
c  Afghanistan  1962    10267083    31.997  853.100710
d  Afghanistan  1967    11537966    34.020  836.197138
e  Afghanistan  1972    13079460    36.088  739.981106

In [84]:
ser = sample["year"]

In [85]:
type(ser)

pandas.core.series.Series

In [86]:
ser

a    1952
b    1957
c    1962
d    1967
e    1972
Name: year, dtype: int64

In [87]:
ser[2]

1962

In [88]:
ser["c"]

1962

In [ ]:
'''
Implicit index- 0 --> iloc
Explicit index - visible --> loc
'''

In [89]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [90]:
df.loc[1]

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [91]:
df.iloc[0]

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [92]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [93]:
df.loc[1:3] #in slicing end is inclusive

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710

In [94]:
df.iloc[1:3] #end index is exclusive in slicing using iloc

       Country  year  Population  life_exp    gdp_cap
2  Afghanistan  1957     9240934    30.332  820.85303
3  Afghanistan  1962    10267083    31.997  853.10071

In [95]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [96]:
df.head(15)

        Country  year  Population  life_exp      gdp_cap
1   Afghanistan  1952     8425333    28.801   779.445314
2   Afghanistan  1957     9240934    30.332   820.853030
3   Afghanistan  1962    10267083    31.997   853.100710
4   Afghanistan  1967    11537966    34.020   836.197138
5   Afghanistan  1972    13079460    36.088   739.981106
6   Afghanistan  1977    14880372    38.438   786.113360
7   Afghanistan  1982    12881816    39.854   978.011439
8   Afghanistan  1987    13867957    40.822   852.395945
9   Afghanistan  1992    16317921    41.674   649.341395
10  Afghanistan  1997    22227415    41.763   635.341351
11  Afghanistan  2002    25268405    42.129   726.734055
12  Afghanistan  2007    31889923    43.828   974.580338
13      Albania  1952     1282697    55.230  1601.056136
14      Albania  1957     1476505    59.280  1942.284244
15      Albania  1962     1728137    64.820  2312.888958

In [97]:
df.iloc[ [1, 10] ] #accessing multiple rows

        Country  year  Population  life_exp     gdp_cap
2   Afghanistan  1957     9240934    30.332  820.853030
11  Afghanistan  2002    25268405    42.129  726.734055

In [98]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [99]:
df.loc[-1]

KeyError: ignored

In [100]:
df.iloc[-1] #last row

Country         Zimbabwe
year                2007
Population      12311143
life_exp          43.487
gdp_cap       469.709298
Name: 1704, dtype: object

In [101]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [102]:
temp = df.set_index("Country")
temp

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
...           ...         ...       ...         ...
Zimbabwe     1987     9216418    62.351  706.157306
Zimbabwe     1992    10704340    60.377  693.420786
Zimbabwe     1997    11404948    46.809  792.449960
Zimbabwe     2002    11926563    39.989  672.038623
Zimbabwe     2007    12311143    43.487  469.709298

[1704 rows x 4 columns]

In [103]:
temp.head()

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106

In [104]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [106]:
temp.loc["Afghanistan"]

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106
Afghanistan  1977    14880372    38.438  786.113360
Afghanistan  1982    12881816    39.854  978.011439
Afghanistan  1987    13867957    40.822  852.395945
Afghanistan  1992    16317921    41.674  649.341395
Afghanistan  1997    22227415    41.763  635.341351
Afghanistan  2002    25268405    42.129  726.734055
Afghanistan  2007    31889923    43.828  974.580338

In [107]:
temp.head()

             year  Population  life_exp     gdp_cap
Country
Afghanistan  1952     8425333    28.801  779.445314
Afghanistan  1957     9240934    30.332  820.853030
Afghanistan  1962    10267083    31.997  853.100710
Afghanistan  1967    11537966    34.020  836.197138
Afghanistan  1972    13079460    36.088  739.981106

In [108]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [109]:
df.reset_index()

      index      Country  year  Population  life_exp     gdp_cap
0         1  Afghanistan  1952     8425333    28.801  779.445314
1         2  Afghanistan  1957     9240934    30.332  820.853030
2         3  Afghanistan  1962    10267083    31.997  853.100710
3         4  Afghanistan  1967    11537966    34.020  836.197138
4         5  Afghanistan  1972    13079460    36.088  739.981106
...     ...          ...   ...         ...       ...         ...
1699   1700     Zimbabwe  1987     9216418    62.351  706.157306
1700   1701     Zimbabwe  1992    10704340    60.377  693.420786
1701   1702     Zimbabwe  1997    11404948    46.809  792.449960
1702   1703     Zimbabwe  2002    11926563    39.989  672.038623
1703   1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 6 columns]

In [110]:
df.reset_index(drop = True)

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [111]:
df.head()

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [112]:
df.reset_index(drop = True, inplace = True)

In [113]:
df.head()

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [114]:
#hw - try reseting for temp

In [115]:
df_sample = df.head()

In [116]:
df_sample

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [117]:
df_sample.drop(columns = ["year"])

       Country  Population  life_exp     gdp_cap
0  Afghanistan     8425333    28.801  779.445314
1  Afghanistan     9240934    30.332  820.853030
2  Afghanistan    10267083    31.997  853.100710
3  Afghanistan    11537966    34.020  836.197138
4  Afghanistan    13079460    36.088  739.981106

In [118]:
df_sample

       Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [119]:
df_sample = df_sample.drop(columns = ["year"])

In [121]:
df_sample

       Country  Population  life_exp     gdp_cap
0  Afghanistan     8425333    28.801  779.445314
1  Afghanistan     9240934    30.332  820.853030
2  Afghanistan    10267083    31.997  853.100710
3  Afghanistan    11537966    34.020  836.197138
4  Afghanistan    13079460    36.088  739.981106